language: node_js
node_js: 
  - 10

install:
  - yarn install   

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN 
  keep_history: false
  name: du_chao_jun
  email: 253867843@qq.com
  on:
    branch: main